flatpak install -y app.devsuite.Ptyxis
flatpak install -y com.borgbase.Vorta
flatpak install -y com.brave.Browser
flatpak install -y com.github.tchx84.Flatseal
flatpak install -y com.google.Chrome
flatpak install -y com.google.EarthPro
flatpak install -y com.mattjakeman.ExtensionManager
flatpak install -y com.rawtherapee.RawTherapee
flatpak install -y com.visualstudio.code
flatpak install -y io.github.dvlv.boxbuddyrs
flatpak install -y io.github.shiftey.Desktop
flatpak install -y io.github.ungoogled_software.ungoogled_chromium
flatpak install -y io.gitlab.librewolf-community
flatpak install -y io.podman_desktop.PodmanDesktop
flatpak install -y net.giuspen.cherrytree
flatpak install -y net.mullvad.MullvadBrowser
flatpak install -y org.darktable.Darktable
flatpak install -y org.fedoraproject.MediaWriter
flatpak install -y org.filezillaproject.Filezilla
flatpak install -y org.freac.freac
flatpak install -y org.freefilesync.FreeFileSync
flatpak install -y org.geany.Geany
flatpak install -y org.gimp.GIMP
flatpak install -y org.gnome.Epiphany
flatpak install -y org.gnome.Logs
flatpak install -y org.gnome.seahorse.Application
flatpak install -y org.keepassxc.KeePassXC
flatpak install -y org.libreoffice.LibreOffice
flatpak install -y org.strawberrymusicplayer.strawberry
flatpak install -y org.videolan.VLC
